-- JusticeLink Database Schema (PostgreSQL / Supabase compatible)

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ENUMS
CREATE TYPE user_role AS ENUM ('Volunteer Attorney', 'Citizen', 'Super Administrator');
CREATE TYPE user_status AS ENUM ('online', 'offline');
CREATE TYPE case_status AS ENUM ('Pending Triage', 'Pending Acceptance', 'In Progress', 'Hearing Scheduled', 'Demand Sent', 'Closed - Won', 'Closed - Lost', 'Withdrawn', 'Dropped');
CREATE TYPE verification_status AS ENUM ('unverified', 'verified', 'rejected');
CREATE TYPE lawyer_preference_type AS ENUM ('Pro Bono', 'Private');

-- 1. USERS (Profiles)
-- Assuming integration with Supabase auth.users, this table acts as the public profile.
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), -- or REFERENCES auth.users(id)
    email VARCHAR(255) UNIQUE,
    handle VARCHAR(100) UNIQUE NOT NULL,
    
    -- Personal Information (from OCR / Setup)
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    suffix VARCHAR(20),
    date_of_birth DATE,
    phone_number VARCHAR(20),
    
    -- Location / Address
    region VARCHAR(100),
    province VARCHAR(100),
    city_municipality VARCHAR(100),
    barangay VARCHAR(100),
    street_address TEXT,

    -- Identity Verification (Didit OCR & Face Match)
    is_didit_verified BOOLEAN DEFAULT false,
    valid_id_number VARCHAR(100),
    valid_id_expiry_date DATE,

    -- Manual Verification (For Legal Professionals & Fallbacks)
    status_verification verification_status DEFAULT 'unverified',
    id_picture_url TEXT,
    selfie_url TEXT,

    -- Legal Professional Details
    firm_name VARCHAR(150),
    ibp_number VARCHAR(50),
    roll_number VARCHAR(50),

    -- System Fields
    role user_role NOT NULL DEFAULT 'Citizen',
    status user_status DEFAULT 'offline',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. CASES
-- Represents a legal case or inquiry associated with a citizen.
CREATE TABLE cases (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    lawyer_preference lawyer_preference_type,
    status case_status DEFAULT 'Pending Triage',
    client_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    attorney_id UUID REFERENCES users(id) ON DELETE SET NULL,
    ai_summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- 3. TRIAGE ASSESSMENTS
-- AI-generated or manual initial assessment for a case.
CREATE TABLE triage_assessments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    issue_type VARCHAR(100) NOT NULL, -- e.g., 'Housing / Eviction', 'Labor Law'
    match_percentage DECIMAL(5, 2), -- e.g., 98.50
    summary TEXT,
    triage_input JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. MESSAGE THREADS
-- Groups messages related to a specific topic or case.
CREATE TABLE message_threads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    case_id UUID REFERENCES cases(id) ON DELETE CASCADE, -- Optional, can be a general thread if null
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Thread Participants (Many-to-Many between Users and Message Threads)
CREATE TABLE thread_participants (
    thread_id UUID REFERENCES message_threads(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (thread_id, user_id)
);

-- 5. MESSAGES
-- Individual messages within a thread.
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    thread_id UUID NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. AUDIT LOGS
-- Tracks system events and actions generated by users for security and auditing.
CREATE TABLE audit_logs (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    action_type VARCHAR(100) NOT NULL, -- e.g., 'Login', 'Security', 'User', 'Action'
    detail TEXT NOT NULL,
    ip_address INET,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. CASE STUDIES
-- Public success stories or educational material for citizen users.
CREATE TABLE case_studies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    outcomes JSONB NOT NULL DEFAULT '[]', -- Array of outcome strings
    tag VARCHAR(100),
    is_published BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ==========================================
-- SAMPLE DATA INSERTION
-- ==========================================

-- Insert Users
INSERT INTO users (id, email, first_name, last_name, handle, role, status, is_didit_verified, status_verification, valid_id_number, valid_id_expiry_date, ibp_number, roll_number, id_expiry_date, phone_number, date_of_birth, id_picture_url, selfie_url) VALUES 
('11111111-1111-1111-1111-111111111111', 'juan.delacruz@example.com', 'Juan', 'Dela Cruz', '@juan', 'Citizen', 'offline', true, 'verified', 'DL-123-456', '2028-06-12', NULL, NULL, NULL, '+63 917 123 4567', '1992-06-12', NULL, NULL),
('22222222-2222-2222-2222-222222222222', 'atty.maria@example.com', 'Maria', 'Santos', '@atty_maria', 'Volunteer Attorney', 'online', false, 'unverified', NULL, NULL, '123456', '98765', '2028-12-31', '+63 918 987 6543', '1988-11-20', 'https://example.com/ibp-id.jpg', 'https://example.com/selfie.jpg'),
('33333333-3333-3333-3333-333333333333', 'admin@justice.link', 'System', 'Admin', '@admin', 'Super Administrator', 'offline', true, 'verified', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Insert Cases
INSERT INTO cases (id, title, description, status, client_id, attorney_id) VALUES 
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Eviction Defense - Dela Cruz Family', 'Facing unjust eviction from our apartment.', 'In Progress', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222'),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Unfair Labor Practice', 'Terminated without just cause.', 'Pending Triage', '11111111-1111-1111-1111-111111111111', NULL);

-- Insert Triage Assessments
INSERT INTO triage_assessments (case_id, issue_type, match_percentage, summary) VALUES 
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Housing / Eviction', 98.00, 'High priority eviction case. Requires immediate legal intervention.'),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Labor Law', 85.50, 'Potential illegal dismissal. Needs review of employment contract.');

-- Insert Message Threads & Participants
INSERT INTO message_threads (id, case_id, name) VALUES 
('cccccccc-cccc-cccc-cccc-cccccccccccc', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Eviction Defense Consultation');

INSERT INTO thread_participants (thread_id, user_id) VALUES 
('cccccccc-cccc-cccc-cccc-cccccccccccc', '11111111-1111-1111-1111-111111111111'),
('cccccccc-cccc-cccc-cccc-cccccccccccc', '22222222-2222-2222-2222-222222222222');

-- Insert Messages
INSERT INTO messages (thread_id, sender_id, content, is_read) VALUES 
('cccccccc-cccc-cccc-cccc-cccccccccccc', '11111111-1111-1111-1111-111111111111', 'Hello Atty, I received an eviction notice today.', true),
('cccccccc-cccc-cccc-cccc-cccccccccccc', '22222222-2222-2222-2222-222222222222', 'Hi Juan. Please send me a copy of the notice so I can review it.', false);

-- Insert Audit Logs
INSERT INTO audit_logs (user_id, action_type, detail, ip_address) VALUES 
('33333333-3333-3333-3333-333333333333', 'Login', 'Admin successfully logged in.', '192.168.1.100'),
('22222222-2222-2222-2222-222222222222', 'Action', 'Atty. Maria accepted case aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa.', '10.0.0.50');

-- Insert Case Studies
INSERT INTO case_studies (title, description, outcomes, tag, is_published) VALUES 
('Successful Eviction Defense in Quezon City', 'A pro bono lawyer helped a family stay in their home after an illegal eviction attempt.', '["Family remained in home", "Landlord penalized"]', 'Tulong sa Housing', true);

-- 8. USER DOCUMENTS
-- Documents generated by AI (or manually uploaded) saved to the user's account
CREATE TABLE user_documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    template_slug VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
