export type RootStackParamList = {
  Auth: undefined;
  PublicHome: undefined;
  PublicCases: undefined;
  PublicMessages: undefined;
  PublicProfile: undefined;
  PublicAttorneyProfile: { attorneyId: string };
  PublicTriage: undefined;
  PublicTriageResult: { result: any };
  PublicTriageLawyerSelection: { result: any };
  PublicDocumentGenerator: undefined;
  PublicDocumentForm: { templateSlug: string; templateTitle: string };
  PublicDocumentResult: { result: any };
  PublicMyDocuments: undefined;
  PublicRightsLibrary: { initialTab?: 'guides' | 'cases' | 'laws'; query?: string; initialSources?: any[] } | undefined;
  PublicLegislationTracker: undefined;
  PublicNotifications: undefined;
  LegalNotifications: undefined;
  ChatThread: { threadId: string; threadName: string };
  CaseDetails: { caseId: string };
  LegalCaseDetails: { caseId: string };
  PersonalInfo: undefined;
  Security: undefined;
  Settings: undefined;
  TermsOfService: undefined;
  PrivacyPolicy: undefined;
  NotificationSettings: undefined;
  LegalHome: undefined;
  AdminHome: undefined;
};

export type Role = 'public' | 'legal' | 'admin';
